name: "Lint Commit Messages"

on:
    push:
        branches-ignore:
            - 'main' # Optional: stops it from running on main if pushed directly
    pull_request:

jobs:
  commitlint:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history so commitlint can check all PR commits

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Validate Commits
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx commitlint --config "@commitlint/config-conventional" --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          else
            npx commitlint --config "@commitlint/config-conventional" --from HEAD~1 --to HEAD --verbose
          fi